import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 1020 } });
const errors = [];
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
await page.goto('http://localhost:4310/components/09-nav/index.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(400);
const stage = await page.locator('.stage').boundingBox();
await page.getByRole('button', { name: 'Mute voice guidance, currently on' }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: 'reviews/09-nav/judge-r1/states/muted.png', clip: stage });
// text scale 2x
const p2 = await browser.newPage({ viewport: { width: 1400, height: 1020 } });
await p2.goto('http://localhost:4310/components/09-nav/index.html', { waitUntil: 'networkidle' });
await p2.addStyleTag({ content: 'html{font-size:30px !important}' });
await p2.waitForTimeout(500);
await p2.screenshot({ path: 'reviews/09-nav/judge-r1/states/textscale.png', clip: stage });
// gaze focus: hover mute button
const p3 = await browser.newPage({ viewport: { width: 1400, height: 1020 } });
await p3.goto('http://localhost:4310/components/09-nav/index.html', { waitUntil: 'networkidle' });
await p3.waitForTimeout(400);
const mb = await p3.locator('button[aria-label*="Mute voice"]').boundingBox();
await p3.mouse.move(mb.x + mb.width/2, mb.y + mb.height/2);
await p3.waitForTimeout(600);
await p3.screenshot({ path: 'reviews/09-nav/judge-r1/states/gaze-focus.png', clip: stage });
await p3.waitForTimeout(900);
await p3.screenshot({ path: 'reviews/09-nav/judge-r1/states/gaze-dwell.png', clip: stage });
console.log(JSON.stringify({ errors }, null, 2));
await browser.close();
